# Generated by Django 5.1.4 on 2025-03-27 17:16

import SourceProg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SourceProg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=SourceProg.models.user_expense_photo_path),
        ),
    ]
