# Generated by Django 5.1.4 on 2025-06-06 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SourceProg', '0004_creditpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(max_length=255, verbose_name='Кому должен')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('taken_date', models.DateField(verbose_name='Дата взятия')),
                ('due_date', models.DateField(verbose_name='Дата возврата')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Отдал?')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата отдачи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
