# Generated by Django 5.1.4 on 2025-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SourceProg', '0005_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='debtor_name',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='debt',
            name='closed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AddField(
            model_name='debt',
            name='direction',
            field=models.CharField(choices=[('i_owe', 'Я должен'), ('they_owe', 'Мне должны')], default='they_owe', max_length=10),
        ),
        migrations.AddField(
            model_name='debt',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыт?'),
        ),
        migrations.AddField(
            model_name='debt',
            name='name',
            field=models.CharField(default='unknown', max_length=255, verbose_name='Имя'),
        ),
    ]
