# Generated by Django 5.1.6 on 2025-03-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='profile_pics/default_avatar.jpg', upload_to='profile_pics/'),
        ),
    ]
