# Generated by Django 5.1.4 on 2025-05-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_category_credit_debt_expense_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
