# Generated by Django 5.1.4 on 2025-05-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_remove_expense_category_remove_credit_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='balance',
        ),
    ]
